// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOWXYitVpInsrYEdtuJSSB2O8YsEQfL1A',
    appId: '1:203378684771:web:43ea7df2cf6ed39cf91956',
    messagingSenderId: '203378684771',
    projectId: 'hilcom-acf15',
    authDomain: 'hilcom-acf15.firebaseapp.com',
    storageBucket: 'hilcom-acf15.firebasestorage.app',
    measurementId: 'G-4BYQEJCDEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qsEjSAwsj0r1Ni11mkkNKiogZblUEA8',
    appId: '1:203378684771:android:6a6f63a7dcb29f84f91956',
    messagingSenderId: '203378684771',
    projectId: 'hilcom-acf15',
    storageBucket: 'hilcom-acf15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmvPIr9n4fGJ0kaTtcAZLfLuFt1q_soTQ',
    appId: '1:203378684771:ios:56810005be51c56bf91956',
    messagingSenderId: '203378684771',
    projectId: 'hilcom-acf15',
    storageBucket: 'hilcom-acf15.firebasestorage.app',
    iosBundleId: 'com.example.hilcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmvPIr9n4fGJ0kaTtcAZLfLuFt1q_soTQ',
    appId: '1:203378684771:ios:56810005be51c56bf91956',
    messagingSenderId: '203378684771',
    projectId: 'hilcom-acf15',
    storageBucket: 'hilcom-acf15.firebasestorage.app',
    iosBundleId: 'com.example.hilcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOWXYitVpInsrYEdtuJSSB2O8YsEQfL1A',
    appId: '1:203378684771:web:05b48925eea9e735f91956',
    messagingSenderId: '203378684771',
    projectId: 'hilcom-acf15',
    authDomain: 'hilcom-acf15.firebaseapp.com',
    storageBucket: 'hilcom-acf15.firebasestorage.app',
    measurementId: 'G-E0F8JPPQM1',
  );
}
